# Generated by Django 3.1.3 on 2020-11-21 23:33

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('definition', models.CharField(max_length=255)),
                ('wikipedia_link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('definition', models.CharField(max_length=255)),
                ('wikipedia_link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyNode',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('definition', models.CharField(max_length=255)),
                ('wikipedia_link', models.CharField(blank=True, max_length=255)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.component')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.stack'),
        ),
    ]
