# Generated by Django 3.1.2 on 2020-10-24 19:29

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyNode',
            fields=[
                ('id', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('definition', models.TextField()),
                ('similar_tech', models.TextField()),
            ],
        ),
    ]
